apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-service
  namespace: finledger
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: transaction-service
  namespaceSelector:
    matchNames:
      - finledger
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ledger-service
  namespace: finledger
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ledger-service
  namespaceSelector:
    matchNames:
      - finledger
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yet-another-cloudwatch-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 60s